# Generated by Django 4.2.3 on 2023-07-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='customer',
            name='landmark',
            field=models.CharField(default='none', max_length=60),
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile_number',
            field=models.IntegerField(default='none'),
        ),
        migrations.AddField(
            model_name='customer',
            name='other_mobile_number',
            field=models.IntegerField(default='none'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('TW', 'Top Wear'), ('BW', 'Bottom Wear'), ('FW', 'Foot Wear'), ('D', 'Digital'), ('H', 'Home'), ('N', 'New Arrivals')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(upload_to='product_img'),
        ),
    ]
