# Generated by Django 4.2.3 on 2023-07-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer_address_customer_landmark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile_number',
            field=models.CharField(default='none', max_length=12),
        ),
        migrations.AlterField(
            model_name='customer',
            name='other_mobile_number',
            field=models.CharField(default='none', max_length=12),
        ),
    ]
