# Generated by Django 4.2.3 on 2023-07-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_customer_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile_number',
            field=models.IntegerField(default=0, max_length=12),
        ),
        migrations.AlterField(
            model_name='customer',
            name='other_mobile_number',
            field=models.CharField(default=0, max_length=12),
        ),
    ]
